DROP DATABASE IF EXISTS Tumblr;
CREATE DATABASE Tumblr;
USE Tumblr;

CREATE TABLE User(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(30)
);

CREATE TABLE Blog(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(30),
number_of_likes INT NULL
);

CREATE TABLE BlogPost(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(30),
blog_id INT,
FOREIGN KEY (blog_id) REFERENCES Blog(id)
);

CREATE TABLE Likes(
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT,
blog_post_id INT,
FOREIGN KEY (user_id) REFERENCES User(id),
FOREIGN KEY (blog_post_id) REFERENCES BlogPost(id)
);