CREATE TABLE house(
	id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(30) NOT NULL,
    number_of_wins INTEGER DEFAULT 0
);

CREATE TABLE person(
	id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(30) NOT NULL,
    house_id INTEGER DEFAULT NULL,
    FOREIGN KEY (house_id) REFERENCES house(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE battle(
	id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	winner_id INTEGER DEFAULT NULL,
    loser_id INTEGER DEFAULT NULL,
    FOREIGN KEY (winner_id) REFERENCES person(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (loser_id) REFERENCES person(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
