DROP DATABASE IF EXISTS Test;
CREATE DATABASE Test;

USE Test;
CREATE TABLE Blog(
	id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(30) NOT NULL,
    number_of_likes INTEGER DEFAULT 0
);

CREATE TABLE BlogPost(
	id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(30) NOT NULL,
    blog_id INTEGER NOT NULL,
    
    FOREIGN KEY (blog_id) REFERENCES Blog(id)
		ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE User(
	id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE Likes(
	id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL,
    blog_post_id INTEGER NOT NULL,
    
    FOREIGN KEY (user_id) REFERENCES User(id)
		ON UPDATE CASCADE
        ON DELETE CASCADE,
        
	FOREIGN KEY (blog_post_id) REFERENCES BlogPost(id)
		ON UPDATE CASCADE
        ON DELETE CASCADE
);