DELIMITER $$
CREATE TRIGGER 1t AFTER UPDATE ON Likes
    FOR EACH ROW 
BEGIN
END$$
CREATE TRIGGER 2t AFTER INSERT ON Likes
    FOR EACH ROW 
BEGIN
	
    
END$$
CREATE TRIGGER 3t AFTER DELETE ON Likes
    FOR EACH ROW 
BEGIN

END$$
DELIMITER ;