DROP DATABASE IF EXISTS elsys_A_10;
CREATE DATABASE elsys_A_10;
USE elsys_A_10;


CREATE TABLE user (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,  
	name VARCHAR(100) NOT NULL,
	username VARCHAR(100) NOT NULL,
    number_of_total_views INTEGER DEFAULT 0
);

CREATE TABLE channel (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,  
	name VARCHAR(100) NOT NULL,
	user_id INTEGER NOT NULL,
    FOREIGN KEY(user_id) REFERENCES user(id)
);

CREATE TABLE video (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,  
	name VARCHAR(100) NOT NULL,
	channel_id INTEGER NOT NULL,
    views INTEGER DEFAULT 0,
    FOREIGN KEY(channel_id) REFERENCES channel(id)
);

CREATE TABLE userChannels (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,  
	channel_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
    FOREIGN KEY(user_id) REFERENCES user(id),
	FOREIGN KEY(channel_id) REFERENCES channel(id)
);