USE Instagram;

INSERT INTO iUser VALUES(NULL, 'Petar', DEFAULT);
INSERT INTO iUser VALUES(NULL, 'Dani', DEFAULT);
INSERT INTO iUser VALUES(NULL, 'Chichu', DEFAULT);

INSERT INTO iPost VALUES(NULL, 'Na plaja', 1);
INSERT INTO iPost VALUES(NULL, 'V baseina', 1);

INSERT INTO iPost VALUES(NULL, 'Generic lyric 1', 2);
INSERT INTO iPost VALUES(NULL, 'Generic lyric 2', 2);

INSERT INTO iPost VALUES(NULL, 'Biceps', 3);
INSERT INTO iPost VALUES(NULL, 'Triceps s filtar', 3);

INSERT INTO iLikes VALUES(NULL, 1, 1);
INSERT INTO iLikes VALUES(NULL, 2, 1);
INSERT INTO iLikes VALUES(NULL, 3, 1);


INSERT INTO iLikes VALUES(NULL, 1, 2);
INSERT INTO iLikes VALUES(NULL, 2, 2);
INSERT INTO iLikes VALUES(NULL, 3, 2);


INSERT INTO iLikes VALUES(NULL, 1, 5);
INSERT INTO iLikes VALUES(NULL, 2, 5);
INSERT INTO iLikes VALUES(NULL, 3, 5);
INSERT INTO iLikes VALUES(NULL, 3, 5);

INSERT INTO iLikes VALUES(NULL, 1, 6);
INSERT INTO iLikes VALUES(NULL, 2, 6);
INSERT INTO iLikes VALUES(NULL, 2, 6);
INSERT INTO iLikes VALUES(NULL, 3, 6);
INSERT INTO iLikes VALUES(NULL, 3, 6);