DROP DATABASE IF EXISTS Youtube;
CREATE DATABASE Youtube;
USE Youtube;

CREATE TABLE User (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE,
    username VARCHAR(200) NOT NULL UNIQUE,
    number_of_total_views INTEGER DEFAULT 0
);

CREATE TABLE Channel (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    user_id INTEGER NOT NULL,
    
    FOREIGN KEY (user_id) REFERENCES User(id)
);

CREATE TABLE Video (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE,
    channel_id INTEGER NOT NULL,
    views INTEGER DEFAULT 0,
    
    FOREIGN KEY (channel_id) REFERENCES Channel(id)
);
