DROP DATABASE IF EXISTS YouTube;
CREATE DATABASE YouTube;
USE YouTube;

CREATE TABLE User(
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    username VARCHAR(40) NOT NULL UNIQUE,
    number_of_total_views INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE Channel(
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    user_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES User(id)
);

CREATE TABLE Video (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    channel_id INTEGER NOT NULL,
    views INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (channel_id) REFERENCES Channel(id)
);
