DROP DATABASE IF EXISTS Youtube;
CREATE DATABASE Youtube;

USE Youtube;

CREATE TABLE YUser(
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	yname VARCHAR(20) NOT NULL,
    username VARCHAR(20) UNIQUE NOT NULL,
    number_of_total_views INTEGER NOT NULL DEFAULT 0
);


CREATE TABLE YChannel(
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	yname VARCHAR(20) NOT NULL,
    user_id INTEGER NOT NULL,
    
    FOREIGN KEY (user_id) REFERENCES YUser(id)
);

CREATE TABLE YVideo(
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	yname VARCHAR(20) NOT NULL,
    channel_id INTEGER NOT NULL,
    views INTEGER NOT NULL DEFAULT 0,
	
    FOREIGN KEY (channel_id) REFERENCES YChannel(id)
);

