DROP DATABASE IF EXISTS tumblr;
CREATE DATABASE tumblr;
USE tumblr;


CREATE TABLE Blog (
	Id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(150) NOT NULL,
    Number_of_likes INTEGER NOT NULL
);

CREATE TABLE BlogPost (
	Id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(150) NOT NULL,
    Blog_id INTEGER NOT NULL,
    
    FOREIGN KEY(Blog_id) REFERENCES Blog(Id)
);

CREATE TABLE User (
	Id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(150) NOT NULL
);

CREATE TABLE Likes (
	Id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,	
    User_id INTEGER NOT NULL,
    Blog_post_id INTEGER NOT NULL,
    
    FOREIGN KEY(User_id) REFERENCES User(Id),
    FOREIGN KEY(Blog_post_id) REFERENCES BlogPost(Id)
);
